routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');

Route::resource('admins', 'AdminController');

Route::resource('countries', 'CountryController');

Route::get('shipment/payment-confirmation', 'ShipmentController@paymentConfirmaion')->name('shipments.payment-confirmation');
Route::post('shipment/payment-confirmation/{id}', 'ShipmentController@confirmPayment')->name('shipments.confirm-payment');

Route::get('shipment/ready-for-shipment', 'ShipmentController@readyForShipment')->name('shipments.ready-for-shipment');
Route::post('shipment/ready-for-shipment', 'ShipmentController@shipped')->name('shipments.shipment');

Route::get('shipment/delivered', 'ShipmentController@readyForDelivered')->name('shipments.ready-for-delivered');
Route::post('shipment/delivered', 'ShipmentController@delivered')->name('shipments.delivered');

Route::resource('shipments', 'ShipmentController');

Route::get('quotations', 'QuotationController@index')->name('quotations.index');
Route::get('quotations/{quotation}', 'QuotationController@show')->name('quotations.show');
Route::put('quotations/{quotation}', 'QuotationController@update')->name('quotations.update');

Route::group(['prefix' => 'shipments/{shipment}'], function () {
    Route::resource('shipment-items', 'ShipmentItemController');
});

Route::get('uk-warehouse-address', 'WarehouseController@index')->name('uk.warehouse.address.index');
Route::post('uk-warehouse-address', 'WarehouseController@store')->name('uk.warehouse.address.store');

Route::group(['prefix' => 'ajax'], function () {
    Route::get('datatable-admins', 'AdminController@indexDatatable');

    Route::get('users/search', 'UserController@search');
    Route::get('datatable-users', 'UserController@indexDatatable');
    Route::get('users/{user}', 'UserController@ajaxShow');

    Route::get('datatable-countries', 'CountryController@indexDatatable');

    Route::get('datatable-shipments', 'ShipmentController@indexDatatable');

    Route::get('datatable-quotations', 'QuotationController@indexDatatable');
    Route::get('datatable-quotations/{quotation}', 'QuotationController@showDatatable');

    Route::post('medias/{type}', 'MediaController@store');
    Route::delete('medias/{media}', 'MediaController@destroy');

    Route::group(['prefix' => 'shipments/{shipment}'], function () {
        Route::get('datatable-shipment-items', 'ShipmentItemController@indexDatatable');
    });
});

routes/front.php
<?php

use Illuminate\Support\Facades\Route;

use App\Models\User;
use App\Models\Shipment;
use App\Models\Quotation;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendMail;

Route::any('test/{user}',
  'RegistrationController@otpCall');
Route::any('test-mail',function(){
  $data['userObj'] = User::find(2);
  $data['mail'] = "Testing mail content";
  $data['subject'] = "Test Mail";
  dd(Mail::to('dev2@cloudsasystems.com')->send(new SendMail($data)));

});
Route::get('test',function(){
  return generateInvoice(31);
});
Route::get('/', 'HomeController@index')->name('home');
Route::get('pricing', 'HomeController@pricing')->name('home.pricing');

Route::get('/thank-you', function () {
    return view('thank-you');
});

Route::get('/parcel-forwarding-service-europe', function () {
    return view('service-europe');
});

Route::get('/package-forwarding-service', function () {
    return view('package-forwarding');
});

Route::get('/parcel-forwarding-service-to-australia', function () {
    return view('forwarding-australia');
});

Route::get('/parcel-forwarding-service-us', function () {
    return view('parcelforwardingus');
});

Route::get('/parcel-delivery-service-uk', function () {
    return view('parcel-delivery-service');
});

Route::get('/parcel-forwarding-service', function () {
    return view('parcel-forwarding-service');
});

Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);
Route::any('xml/{user}', 'XmlController@index')->name('xml.index');
Route::post('read-notifications', 'Admin\UserController@readNotification');
Route::get('registration/plan', 'RegistrationController@plan')->name('registration.plan');
Route::get('services', 'HomeController@services');
Route::get('contact-us', 'ContactUsController@index');
Route::post('contact-us', 'ContactUsController@store')->name('contact-us.store');
//Route::get('blog', 'HomeController@blog');
//Route::get('blog-detail', 'HomeController@blogDetail');
Route::get('faqs', 'HomeController@faqs');
Route::get('privacy-policy', 'HomeController@privacy');
Route::get('terms-trade', 'HomeController@termsTrade');
Route::get('return-policy', 'HomeController@returnPolicy');
Route::get('legal-terms', 'HomeController@legalTerms');
Route::get('sitemap', 'HomeController@sitemap');
Route::get('shipment/{id}', 'HomeController@getPdf');
Route::get('personal-shopper-pdf/{id}', 'HomeController@getPersonalShopperPdf');
Route::get('membership-pdf/{id}', 'HomeController@membershipPdf');

Route::match(['get', 'post'], 'users/{user}/payment', 'RegistrationController@payment')->name('users.payment');

Route::post('payment-gateway', 'PaymentController@index')->name('payment-gateway.index');
Route::post('payment-gateway/pay', 'PaymentController@store')->name('payment-gateway.store');

Route::post('shipping-options', 'ShipmentController@shippingOptions');

Route::post('paypal/express-checkout', 'PaypalController@expressCheckout')->name('paypal.checkout');
Route::get('paypal/express-checkout-success', 'PaypalController@expressCheckoutSuccess');

Route::get('users/verification/{token}', 'RegistrationController@verification')->name('users.verification');
Route::get('users/{user}/verification', 'RegistrationController@verificationStatus')->name('users.verification.status');
Route::get('users/{user}/otp-verification', 'RegistrationController@otpVerification')->name('users.verification.mobile');
Route::get('users/{user}/otp', 'RegistrationController@otpVerificationPage')->name('users.verification.otp');
Route::post('users/{user}/otp-verification', 'RegistrationController@otpVerificationCheck')->name('users.verification.mobile.check');
Route::get('users/resend/verification/{user}', 'RegistrationController@resendVerification')->name('users.resend.verification');
Route::group(['prefix' => 'ajax'], function () {
    Route::post('users/{user}/otp-call', 'RegistrationController@otpCall')->name('users.verification.call');
});
Route::group(['middleware' => 'guest'], function () {
    Route::get('registration/membership', 'RegistrationController@membership')->name('registration.membership');
    Route::post('registration', 'RegistrationController@store')->name('registration.store');

    Route::get('signin', 'LoginController@index')->name('login.index');

    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    Route::get('validate-otp/{token}', 'ResetPasswordController@showValidateOtpForm')->name('password.otp-validation');
    Route::post('validate-otp', 'ResetPasswordController@validateOtp');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset.store');

    Route::group(['prefix' => 'ajax'], function () {
        Route::post('login', 'LoginController@store')->name('login.store');
        Route::post('google-authentication', 'LoginController@googleAuthenticationStore')->name('login.authy.store');
        Route::post('registration/unique', 'RegistrationController@unique');

        Route::post('subscribe','HomeController@subscribe');
    });
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', 'LoginController@logout')->name('logout');


    Route::get('dashboard/', 'UserController@profile')->name('users.profile.index');
    Route::post('profile', 'UserController@profileUpdate')->name('users.profile.update');

    Route::get('security', 'UserController@security')->name('users.security.index');
    Route::post('security', 'UserController@securityUpdate')->name('users.security.update');
    //
    // Route::get('twofactor/enable', 'UserController@enableTwoFactor')->name('users.twofactor.enable');
    // Route::get('twofactor/disable', 'UserController@disableTwoFactor')->name('users.twofactor.disable');

    Route::get('personal-shopper', 'PersonalShopperController@index')->name('users.shopper.index');
    Route::post('personal-shopper', 'PersonalShopperController@store')->name('users.shopper.store');

    Route::post('shipments/{shipment}/shipping-option', 'UserController@shippingOption')->name('users.shipment.shipping-option');
    Route::post('shipments/{shipment}/warehouse-option', 'UserController@warehouseOption')->name('users.shipment.warehouse-option');
    Route::get('users/subscription', 'UserController@subscription')->name('users.subscription');

    Route::post('users/downgrade', 'UserController@downGradeAccount')->name('users.downgrade');

    Route::get('shipments/{shipment}/payment', 'ShipmentPaymentController@index')->name('shipments.payment');
    Route::get('personal-shopper/{quotation}/payment', 'PersonalShopperController@payment')->name('shopper.payment');

    Route::get('dashboard-action', 'HomeController@dashboardAction');
    Route::get('dashboard-history', 'UserController@dashboardHistory');
    Route::get('dashboard-shipments', 'UserController@dashboardShipments');
    Route::get('dashboard-invoice', 'UserController@dashboardInvoice');
    Route::get('dashboard-shipping', 'UserController@dashboardShipping')->name('users.shipments.ready-for-shipment');
    Route::get('dashboard-warehouse', 'HomeController@dashboardWarehouse');
    Route::get('dashboard-action-box', 'UserController@actionbox')->name('users.action_box');
    Route::get('dashboard-warehouse', 'UserController@warehouse')->name('users.warehouse');

    Route::get('get-service-charge', 'HomeController@getServiceCharge');


    Route::group(['prefix' => 'ajax'], function () {
        Route::post('users/shipments/{shipment}/shipment-items/{shipment_item}/request-photo', 'UserController@requestItemPhoto');
        Route::post('users/shipments/{shipment}/shipment-items/{shipment_item}/photos', 'UserController@itemPhotos');

        Route::post('check-mobile', 'UserController@checkMobile');
        Route::post('profile-verify-otp', 'UserController@otpVerificationCheck');
        Route::post('profile-send-otp', 'UserController@sendOtp');
		    Route::post('update-number', 'RegistrationController@updateNumber')->name('users.update.number');

    });
});

Route::group(['middleware' => 'authenticate','prefix' => 'ajax'], function () {
	Route::post('read-notifications', 'Ajax\UserController@readNotification');
	  Route::post('user/autorenew', 'Ajax\PaymentController@autorenew');
      Route::get('profile', 'Ajax\UserController@show');
      Route::post('get-payment-detail', 'Ajax\UserController@paymentDetail');
      Route::post('upload-profile-pic', 'Ajax\UserController@uploadProfilePic');
      Route::post('send-otp', 'Ajax\UserController@sendOtp');
      Route::post('verify-otp', 'Ajax\UserController@verifyOtp');
      Route::post('profile', 'Ajax\UserController@update');
      Route::get('action-box', 'Ajax\UserController@actionBox');
      Route::get('warehouse', 'Ajax\UserController@warehouse');
      Route::get('invoice', 'Ajax\InvoiceController@index');
      Route::get('ready-for-shipping', 'Ajax\UserController@readyForShipping');
      Route::get('shipments', 'Ajax\UserController@shipments');
      Route::get('history', 'Ajax\UserController@history');
      Route::get('security-question', 'Ajax\SecurityQuestionController@index');
      Route::post('security-update', 'Ajax\SecurityQuestionController@securityUpdate');
      Route::post('user/shipment/{shipment}/shipment-item/{shipment_item}/request-photo', 'Ajax\UserController@requestItemPhoto');
      Route::post('shipment/get-shipping-option', 'Ajax\ShipmentController@shippingOptions');
      Route::post('shipment/{shipment}/shipping-option', 'Ajax\UserController@shippingOptions');
      Route::get('personal-shopper', 'Ajax\PersonalShopperController@index');
      Route::post('personal-shopper', 'Ajax\PersonalShopperController@store');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Country;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    public function index()
    {
        $data = [];
        $data['roles'] = config('site.roles');
        return view('admin.pages.users.index', $data);
    }

    public function create()
    {

    }

    public function store()
    {

    }

    public function edit(User $user)
    {

    }

    public function update(User $user)
    {

    }

    public function destroy(User $user)
    {

    }

    public function indexDatatable()
    {
        $data = User::select('*')
            ->where('role_id', '=', '2');

        return DataTables::of($data)
            ->addColumn('action', function ($row) {
                $str = '';
//                $str .= '<a href="' . url()->route('admin.users.edit', $row->id) . '"  data-id="' . $row->id . '" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details">
//							<i class="la la-edit"></i>
//						</a>
//						<a href="#" data-id="' . $row->id . '" class="deleteIndicator m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">
//							<i class="la la-trash"></i>
//						</a>';
                $str .= '<a href="#nogo"  data-id="' . $row->id . '" class="viewUserInfo m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details">
							<i class="la la-eye"></i>
						</a>';
                return $str;
            })
            ->make(true);
    }

    public function ajaxShow(User $user)
    {
        $data = [];
        $user->first_name = ucwords(strtolower($user->first_name));
        $user->last_name = ucwords(strtolower($user->last_name));
        $user->gender = config('site.gender')[$user->gender];

        $cd_country = Country::find($user->cd_country);
        if ($cd_country != null) {
            $user->cd_country = $cd_country->name;
            $user->cd_country_code = $cd_country->country_code;
            $user->cd_suite_number = $cd_country->suite_number;
        }

        $ba_country = Country::find($user->ba_country);
        if ($ba_country != null) {
            $user->ba_country = $ba_country->name;
            $user->ba_country_code = $ba_country->country_code;
            $user->ba_suite_number = $ba_country->suite_number;
        }

        $data['user'] = $user;
        return $data;
    }

    public function search()
    {
        $data = [];

        $data['items'] = User::select(DB::raw('concat(first_name," ",last_name,"-",customer_code) as name'), 'id')
            ->where('first_name', 'like', '%' . request('q') . '%')
            ->orwhere('last_name', 'like', '%' . request('q') . '%')
            ->orwhere(DB::raw('concat(first_name," ",last_name)'), 'like', '%' . request('q') . '%')
            ->orwhere('customer_code', 'like', '%' . request('q') . '%')
            ->get();

        return $data;
    }
}

resources/views/admin/pages/users/create.blade.php
@extends('admin.layouts.master')

@section('contentHeader')
    <link rel="stylesheet" href="{!! asset(mix('css/admin/vendor/croppie.css')) !!}">
@stop

@section('page_title')
    @if(isset($myprofile) && $myprofile)
        Profile
    @elseif(isset($admin))
        Edit Admin
    @else
        Create Admin
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <!--begin::Portlet-->
            <div class="m-portlet">
                <!--begin::Form-->
                @if(isset($myprofile) && $myprofile)
                    {!!Form::model($user,['route'=>'admin.myprofile.store','class'=>'m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed'])!!}
                @elseif(isset($admin))
                    {!!Form::model($admin,['route'=>['admin.admins.update',$admin->id],'method'=>'put','class'=>'m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed'])!!}
                @else
                    {!!Form::open(['route'=>'admin.admins.store','class'=>'m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed'])!!}
                @endif
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-lg-4 @if($errors->has('first_name'))has-danger @endif">
                            {!!Form::label('first_name','First Name')!!}
                            {!!Form::text('first_name', old('first_name'), ['class'=>'form-control','placeholder'=>'First Name'])!!}
                            @if($errors->has('first_name'))
                                <p class="form-control-feedback">{!!$errors->first('first_name')!!}</p>
                            @endif
                        </div>
                        <div class="col-lg-4 @if($errors->has('last_name'))has-danger @endif">
                            {!!Form::label('last_name','Last Name')!!}
                            {!!Form::text('last_name', old('last_name'), ['class'=>'form-control','placeholder'=>'Last Name'])!!}
                            @if($errors->has('last_name'))
                                <p class="form-control-feedback">{!!$errors->first('last_name')!!}</p>
                            @endif
                        </div>
                        <div class="col-lg-4 @if($errors->has('email'))has-danger @endif">
                            {!!Form::label('email','Email')!!}
                            @if(isset($myprofile) && $myprofile)
                                {!!Form::email('email', old('email'), ['class'=>'form-control','placeholder'=>'Email','disabled'])!!}
                            @else
                                {!!Form::email('email', old('email'), ['class'=>'form-control','placeholder'=>'Email'])!!}
                            @endif
                            @if($errors->has('email'))
                                <p class="form-control-feedback">{!!$errors->first('email')!!}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg-4 @if($errors->has('password'))has-danger @endif">
                            {!!Form::label('password','Password')!!}
                            {!!Form::password('password', ['class'=>'form-control','placeholder'=>'Password'])!!}
                            @if($errors->has('password'))
                                <p class="form-control-feedback">{!!$errors->first('password')!!}</p>
                            @endif
                        </div>
                        <div class="col-lg-4">
                            {!!Form::label('password_confirmation','Confirm Password')!!}
                            {!!Form::password('password_confirmation', ['class'=>'form-control','placeholder'=>'Confirm Password'])!!}
                            @if($errors->has('password_confirmation'))
                                <p class="form-control-feedback">{!!$errors->first('password_confirmation')!!}</p>
                            @endif
                        </div>
                    </div>
                </div>
                {{--<div class="form-group m-form__group row">
                    <div class="col-lg-6">
                        <label for="">Profile Pic</label>
                        <div class="ss-crop ss-crop--cover">
                            <div class="ss-crop__wrap">
                                <div class="ss-crop__preview">
                                    <div id="profilePicture-preview"></div>
                                </div>
                                <input type="hidden" name="image" id="profilePicture_hidden">
                                <input type="file" accept="image/x-png,image/gif,image/jpeg" name="" value=""
                                       id="profilePicture" class="ss-crop__file">
                                <label for="profilePicture" class="ss-crop__select">
                                    @if(isset($user) && $user->profile!=null)
                                        <img src="{!! asset($user->profile_path.'/'.$user->profile) !!}"
                                             alt=""/>
                                    @else
                                        <img src="{!! asset('img/user4.jpg') !!}" alt=""/>
                                    @endif
                                    <span type="button" class="btn btn-primary">Change Pic</span>
                                </label>
                            </div>
                            <div class="">
                                <a href="javascript:;" class="ss-crop__reset">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>--}}
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-secondary">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            {!!Form::close()!!}
            <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
@stop

@section('contentFooter')
    <script src="{!! asset(mix('js/admin/vendor/ss-crop.js')) !!}"></script>
    <script>
        $('#role').select2({
            placeholder: "Role"
        });
        $('#profilePicture').ssCrop({
            croppie: {
                viewport: {
                    width: 300,
                    height: 300,
                }
            },
            result: {
                size: {
                    width: 300,
                    format: 'jpeg'
                }
            }
        });
    </script>
@stop

resources/views/admin/pages/users/index.blade.php
@extends('admin.layouts.master')

@section('contentHeader')

@stop

@section('page_title')
    Users
@stop

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__body">
            <!--begin: Search Form -->
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">
                        <div class="form-group m-form__group row align-items-center">
                            <div class="col-md-4">
                                <div class="m-input-icon m-input-icon--left">
                                    <input type="text" class="form-control m-input m-input--solid"
                                           placeholder="Search..." id="generalSearch">
                                    <span class="m-input-icon__icon m-input-icon__icon--left">
                                        <span>
                                            <i class="la la-search"></i>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        {{--<a href="{!! url()->route('admin.admins.create') !!}"
                           class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                            <span>
                                <i class="m-nav__link-icon flaticon-add"></i>
                                <span>
                                    New Admin
                                </span>
                            </span>
                        </a>--}}
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            <!--end: Search Form -->
            <!--begin: Datatable -->
            <table class="table m-table m-table--head-bg-metal  table-striped" id="dataTable">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
                </thead>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
    @include('admin.popups.users_info')
@stop

@section('contentFooter')
    <script>
        $('#users_roles').selectpicker();

        var dTable = $('#dataTable').DataTable({
            ajax: {
                url: adminAjaxURL + 'datatable-users',
                data: function (d) {
                    d.search['value'] = $('#generalSearch').val();
                }
            },
            columns: [
                {data: 'id', name: 'id', className: 'dt-center', searchable: false},
                {data: 'first_name', name: 'users.first_name', className: 'dt-center'},
                {data: 'last_name', name: 'users.last_name', className: 'dt-center'},
                {data: 'email', name: 'users.email', className: 'dt-center'},
                {data: 'action', searchable: false, orderable: false, className: 'dt-center'},
            ],
            order: [[0, 'desc']]
        });

        $('#generalSearch').on('keydown keyup blur change', $.debounce(500, function () {
            dTable.draw();
        }));

        $('#users_roles').change($.debounce(500, function () {
            dTable.draw();
        }));

        $(document).on('click', '.viewUserInfo', function (e) {
            e.preventDefault();
            $.ajax({
                dataType: 'json',
                method: 'get',
                url: adminAjaxURL + 'users/' + $(this).data('id'),
                success: function (data) {
                    var user = data['user'];
                    $('#usersInfoModal').find('#modal_title').text(user['first_name'] + ' ' + user['last_name']);
                    if (user['same_as_cd'] == 1) {
                        $('#usersInfoModal').find('#biling_details_same').show();
                        $('#usersInfoModal').find('#biling_details').hide();
                    } else {
                        $('#usersInfoModal').find('#biling_details_same').hide();
                        $('#usersInfoModal').find('#biling_details').show();
                    }
                    for (var index in user) {
                        $('#usersInfoModal').find('#' + index).text(user[index]);
                    }
                    $('#usersInfoModal').modal('show');
                }
            })
        });


        $(document).on('click', '.deleteAdmin', function (e) {
            e.preventDefault();
            if (confirm('Are you sure you want to delete this user?')) {
                $.ajax({
                    dataType: 'json',
                    method: 'delete',
                    url: adminURL + "users/" + $(this).data('id'),
                    success: function (data) {
                        dTable.draw(false);
                    }
                });
            }
        });
    </script>
@stop