routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');

Route::resource('admins', 'AdminController');

Route::resource('countries', 'CountryController');

Route::get('shipment/payment-confirmation', 'ShipmentController@paymentConfirmaion')->name('shipments.payment-confirmation');
Route::post('shipment/payment-confirmation/{id}', 'ShipmentController@confirmPayment')->name('shipments.confirm-payment');

Route::get('shipment/ready-for-shipment', 'ShipmentController@readyForShipment')->name('shipments.ready-for-shipment');
Route::post('shipment/ready-for-shipment', 'ShipmentController@shipped')->name('shipments.shipment');

Route::get('shipment/delivered', 'ShipmentController@readyForDelivered')->name('shipments.ready-for-delivered');
Route::post('shipment/delivered', 'ShipmentController@delivered')->name('shipments.delivered');

Route::resource('shipments', 'ShipmentController');

Route::get('quotations', 'QuotationController@index')->name('quotations.index');
Route::get('quotations/{quotation}', 'QuotationController@show')->name('quotations.show');
Route::put('quotations/{quotation}', 'QuotationController@update')->name('quotations.update');

Route::group(['prefix' => 'shipments/{shipment}'], function () {
    Route::resource('shipment-items', 'ShipmentItemController');
});

Route::get('uk-warehouse-address', 'WarehouseController@index')->name('uk.warehouse.address.index');
Route::post('uk-warehouse-address', 'WarehouseController@store')->name('uk.warehouse.address.store');

Route::group(['prefix' => 'ajax'], function () {
    Route::get('datatable-admins', 'AdminController@indexDatatable');

    Route::get('users/search', 'UserController@search');
    Route::get('datatable-users', 'UserController@indexDatatable');
    Route::get('users/{user}', 'UserController@ajaxShow');

    Route::get('datatable-countries', 'CountryController@indexDatatable');

    Route::get('datatable-shipments', 'ShipmentController@indexDatatable');

    Route::get('datatable-quotations', 'QuotationController@indexDatatable');
    Route::get('datatable-quotations/{quotation}', 'QuotationController@showDatatable');

    Route::post('medias/{type}', 'MediaController@store');
    Route::delete('medias/{media}', 'MediaController@destroy');

    Route::group(['prefix' => 'shipments/{shipment}'], function () {
        Route::get('datatable-shipment-items', 'ShipmentItemController@indexDatatable');
    });
});

routes/front.php
<?php

use Illuminate\Support\Facades\Route;

use App\Models\User;
use App\Models\Shipment;
use App\Models\Quotation;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendMail;

Route::any('test/{user}',
  'RegistrationController@otpCall');
Route::any('test-mail',function(){
  $data['userObj'] = User::find(2);
  $data['mail'] = "Testing mail content";
  $data['subject'] = "Test Mail";
  dd(Mail::to('dev2@cloudsasystems.com')->send(new SendMail($data)));

});
Route::get('test',function(){
  return generateInvoice(31);
});
Route::get('/', 'HomeController@index')->name('home');
Route::get('pricing', 'HomeController@pricing')->name('home.pricing');

Route::get('/thank-you', function () {
    return view('thank-you');
});

Route::get('/parcel-forwarding-service-europe', function () {
    return view('service-europe');
});

Route::get('/package-forwarding-service', function () {
    return view('package-forwarding');
});

Route::get('/parcel-forwarding-service-to-australia', function () {
    return view('forwarding-australia');
});

Route::get('/parcel-forwarding-service-us', function () {
    return view('parcelforwardingus');
});

Route::get('/parcel-delivery-service-uk', function () {
    return view('parcel-delivery-service');
});

Route::get('/parcel-forwarding-service', function () {
    return view('parcel-forwarding-service');
});

Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);
Route::any('xml/{user}', 'XmlController@index')->name('xml.index');
Route::post('read-notifications', 'Admin\UserController@readNotification');
Route::get('registration/plan', 'RegistrationController@plan')->name('registration.plan');
Route::get('services', 'HomeController@services');
Route::get('contact-us', 'ContactUsController@index');
Route::post('contact-us', 'ContactUsController@store')->name('contact-us.store');
//Route::get('blog', 'HomeController@blog');
//Route::get('blog-detail', 'HomeController@blogDetail');
Route::get('faqs', 'HomeController@faqs');
Route::get('privacy-policy', 'HomeController@privacy');
Route::get('terms-trade', 'HomeController@termsTrade');
Route::get('return-policy', 'HomeController@returnPolicy');
Route::get('legal-terms', 'HomeController@legalTerms');
Route::get('sitemap', 'HomeController@sitemap');
Route::get('shipment/{id}', 'HomeController@getPdf');
Route::get('personal-shopper-pdf/{id}', 'HomeController@getPersonalShopperPdf');
Route::get('membership-pdf/{id}', 'HomeController@membershipPdf');

Route::match(['get', 'post'], 'users/{user}/payment', 'RegistrationController@payment')->name('users.payment');

Route::post('payment-gateway', 'PaymentController@index')->name('payment-gateway.index');
Route::post('payment-gateway/pay', 'PaymentController@store')->name('payment-gateway.store');

Route::post('shipping-options', 'ShipmentController@shippingOptions');

Route::post('paypal/express-checkout', 'PaypalController@expressCheckout')->name('paypal.checkout');
Route::get('paypal/express-checkout-success', 'PaypalController@expressCheckoutSuccess');

Route::get('users/verification/{token}', 'RegistrationController@verification')->name('users.verification');
Route::get('users/{user}/verification', 'RegistrationController@verificationStatus')->name('users.verification.status');
Route::get('users/{user}/otp-verification', 'RegistrationController@otpVerification')->name('users.verification.mobile');
Route::get('users/{user}/otp', 'RegistrationController@otpVerificationPage')->name('users.verification.otp');
Route::post('users/{user}/otp-verification', 'RegistrationController@otpVerificationCheck')->name('users.verification.mobile.check');
Route::get('users/resend/verification/{user}', 'RegistrationController@resendVerification')->name('users.resend.verification');
Route::group(['prefix' => 'ajax'], function () {
    Route::post('users/{user}/otp-call', 'RegistrationController@otpCall')->name('users.verification.call');
});
Route::group(['middleware' => 'guest'], function () {
    Route::get('registration/membership', 'RegistrationController@membership')->name('registration.membership');
    Route::post('registration', 'RegistrationController@store')->name('registration.store');

    Route::get('signin', 'LoginController@index')->name('login.index');

    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    Route::get('validate-otp/{token}', 'ResetPasswordController@showValidateOtpForm')->name('password.otp-validation');
    Route::post('validate-otp', 'ResetPasswordController@validateOtp');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset.store');

    Route::group(['prefix' => 'ajax'], function () {
        Route::post('login', 'LoginController@store')->name('login.store');
        Route::post('google-authentication', 'LoginController@googleAuthenticationStore')->name('login.authy.store');
        Route::post('registration/unique', 'RegistrationController@unique');

        Route::post('subscribe','HomeController@subscribe');
    });
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', 'LoginController@logout')->name('logout');


    Route::get('dashboard/', 'UserController@profile')->name('users.profile.index');
    Route::post('profile', 'UserController@profileUpdate')->name('users.profile.update');

    Route::get('security', 'UserController@security')->name('users.security.index');
    Route::post('security', 'UserController@securityUpdate')->name('users.security.update');
    //
    // Route::get('twofactor/enable', 'UserController@enableTwoFactor')->name('users.twofactor.enable');
    // Route::get('twofactor/disable', 'UserController@disableTwoFactor')->name('users.twofactor.disable');

    Route::get('personal-shopper', 'PersonalShopperController@index')->name('users.shopper.index');
    Route::post('personal-shopper', 'PersonalShopperController@store')->name('users.shopper.store');

    Route::post('shipments/{shipment}/shipping-option', 'UserController@shippingOption')->name('users.shipment.shipping-option');
    Route::post('shipments/{shipment}/warehouse-option', 'UserController@warehouseOption')->name('users.shipment.warehouse-option');
    Route::get('users/subscription', 'UserController@subscription')->name('users.subscription');

    Route::post('users/downgrade', 'UserController@downGradeAccount')->name('users.downgrade');

    Route::get('shipments/{shipment}/payment', 'ShipmentPaymentController@index')->name('shipments.payment');
    Route::get('personal-shopper/{quotation}/payment', 'PersonalShopperController@payment')->name('shopper.payment');

    Route::get('dashboard-action', 'HomeController@dashboardAction');
    Route::get('dashboard-history', 'UserController@dashboardHistory');
    Route::get('dashboard-shipments', 'UserController@dashboardShipments');
    Route::get('dashboard-invoice', 'UserController@dashboardInvoice');
    Route::get('dashboard-shipping', 'UserController@dashboardShipping')->name('users.shipments.ready-for-shipment');
    Route::get('dashboard-warehouse', 'HomeController@dashboardWarehouse');
    Route::get('dashboard-action-box', 'UserController@actionbox')->name('users.action_box');
    Route::get('dashboard-warehouse', 'UserController@warehouse')->name('users.warehouse');

    Route::get('get-service-charge', 'HomeController@getServiceCharge');


    Route::group(['prefix' => 'ajax'], function () {
        Route::post('users/shipments/{shipment}/shipment-items/{shipment_item}/request-photo', 'UserController@requestItemPhoto');
        Route::post('users/shipments/{shipment}/shipment-items/{shipment_item}/photos', 'UserController@itemPhotos');

        Route::post('check-mobile', 'UserController@checkMobile');
        Route::post('profile-verify-otp', 'UserController@otpVerificationCheck');
        Route::post('profile-send-otp', 'UserController@sendOtp');
		    Route::post('update-number', 'RegistrationController@updateNumber')->name('users.update.number');

    });
});

Route::group(['middleware' => 'authenticate','prefix' => 'ajax'], function () {
	Route::post('read-notifications', 'Ajax\UserController@readNotification');
	  Route::post('user/autorenew', 'Ajax\PaymentController@autorenew');
      Route::get('profile', 'Ajax\UserController@show');
      Route::post('get-payment-detail', 'Ajax\UserController@paymentDetail');
      Route::post('upload-profile-pic', 'Ajax\UserController@uploadProfilePic');
      Route::post('send-otp', 'Ajax\UserController@sendOtp');
      Route::post('verify-otp', 'Ajax\UserController@verifyOtp');
      Route::post('profile', 'Ajax\UserController@update');
      Route::get('action-box', 'Ajax\UserController@actionBox');
      Route::get('warehouse', 'Ajax\UserController@warehouse');
      Route::get('invoice', 'Ajax\InvoiceController@index');
      Route::get('ready-for-shipping', 'Ajax\UserController@readyForShipping');
      Route::get('shipments', 'Ajax\UserController@shipments');
      Route::get('history', 'Ajax\UserController@history');
      Route::get('security-question', 'Ajax\SecurityQuestionController@index');
      Route::post('security-update', 'Ajax\SecurityQuestionController@securityUpdate');
      Route::post('user/shipment/{shipment}/shipment-item/{shipment_item}/request-photo', 'Ajax\UserController@requestItemPhoto');
      Route::post('shipment/get-shipping-option', 'Ajax\ShipmentController@shippingOptions');
      Route::post('shipment/{shipment}/shipping-option', 'Ajax\UserController@shippingOptions');
      Route::get('personal-shopper', 'Ajax\PersonalShopperController@index');
      Route::post('personal-shopper', 'Ajax\PersonalShopperController@store');

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;

class Country extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'nice_name',
        'short_code',
        'country_code',
        'suite_number',
        'iso'
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public static function validationRules($id = 0)
    {
        return [
            'name'         => 'required',
            'country_code' => 'required|numeric|unique:countries,country_code,' . $id,
            'suite_number' => 'required|unique:countries,suite_number,' . $id,
            'iso'          => 'required|unique:countries,iso,' . $id
        ];
    }

    public static function getShortCodeByIsoCode($iso)
    {
        return Country::where('iso',$iso)->first();
    }

    public static function search($input)
    {
      $searchQuery = isset($input['query']) ? $input['query'] : [];

      $users = Country::select(DB::raw('SQL_CALC_FOUND_ROWS countries.id'),'name', 'nice_name', 'short_code', 'country_code',
      'suite_number', 'iso');

      if(isset($searchQuery['short_code'])){
        $users->where('short_code',$searchQuery['short_code']);
      }

      if(isset($searchQuery['country_code'])){
        $users->where('country_code',$searchQuery['country_code']);
      }

      if(isset($searchQuery['name'])){
        $users->where('name','like','%'.$searchQuery['name'].'%');
      }

      if(isset($searchQuery['nice_name'])){
        $users->where('nice_name','like','%'.$searchQuery['nice_name'].'%');
      }

      if(isset($searchQuery['suite_number'])){
        $users->where('suite_number','like','%'.$searchQuery['suite_number'].'%');
      }

      if(isset($searchQuery['iso'])){
        $users->where('iso','like','%'.$searchQuery['iso'].'%');
      }

      if(isset($input['page'])){
        $start = $input['limit'] * ($input['page'] - 1);
        $end = $input['limit'];
        $users->skip($start)->take($end);
      }

      $orderBy = isset($input['orderBy']) ? $input['orderBy'] : 'id';
      $order = "desc";
      if(isset($input['ascending']) && $input['ascending'] == "1"){
        $order = "asc";
      }
      $users->orderBy($orderBy,$order);

        $data['country'] = $users->get();
        $data['count']  = DB::select(DB::raw("select FOUND_ROWS() as count"))[0]->count;
        return $data;
    }
}

app/Http/Controllers/Admin/CountryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Country;
use Yajra\DataTables\Facades\DataTables;

class CountryController extends Controller
{
    public function index()
    {
        return view('admin.pages.countries.index');
    }

    public function create()
    {
        return view('admin.pages.countries.create');
    }

    public function store()
    {
        $this->validate(request(), Country::validationRules());

        $country = new Country(request()->all());
        if (!$country->save()) {
            session()->flash('message', 'Something went wrong.');
            session()->flash('class', 'danger');
        }
        session()->flash('message', 'Country added successfully.');
        session()->flash('class', 'success');
        return redirect()->route('admin.countries.index');
    }

    public function edit(Country $country)
    {
        $data = [];
        $data['country'] = $country;
        return view('admin.pages.countries.create', $data);
    }

    public function update(Country $country)
    {
        $this->validate(request(), Country::validationRules($country->id));

        $inputs = request()->all();

        if (!$country->update($inputs)) {
            session()->flash('message', 'Something went wrong.');
            session()->flash('class', 'danger');
            return back();
        }
        session()->flash('message', 'Country updated successfully.');
        session()->flash('class', 'success');
        return redirect()->route('admin.countries.index');
    }

    public function destroy(Country $country)
    {
        $data = [];
        $data['status'] = $country->delete();
        return $data;
    }

    public function indexDatatable()
    {
        $data = Country::select('*');

        return DataTables::of($data)
            ->addColumn('action', function ($row) {
                $str = '';
                $str .= '<a href="' . url()->route('admin.countries.edit', $row->id) . '"  data-id="' . $row->id . '" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details">
							<i class="la la-edit"></i>
						</a>
						<a href="#" data-id="' . $row->id . '" class="deleteCountry m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">
							<i class="la la-trash"></i>
						</a>';
                return $str;
            })
            ->make(true);
    }
}

resources/views/admin/pages/countries/create.blade.php
@extends('admin.layouts.master')

@section('contentHeader')
@stop

@section('page_title')
    @if(isset($country))
        Edit Country
    @else
        Create Country
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-lg-8">
            <!--begin::Portlet-->
            <div class="m-portlet">
                <!--begin::Form-->
                @if(isset($country))
                    {!!Form::model($country,['route'=>['admin.countries.update',$country->id],'method'=>'put','class'=>'m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed'])!!}
                @else
                    {!!Form::open(['route'=>'admin.countries.store','class'=>'m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed'])!!}
                @endif
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-lg-6 @if($errors->has('name'))has-danger @endif">
                            {!!Form::label('name','Name')!!}
                            {!!Form::text('name', old('name'), ['class'=>'form-control','placeholder'=>'Name'])!!}
                            @if($errors->has('name'))
                                <p class="form-control-feedback">{!!$errors->first('name')!!}</p>
                            @endif
                        </div>
                        <div class="col-lg-6 @if($errors->has('iso'))has-danger @endif">
                            {!!Form::label('iso','ISO')!!}
                            {!!Form::text('iso', old('iso'), ['class'=>'form-control','placeholder'=>'ISO'])!!}
                            @if($errors->has('iso'))
                                <p class="form-control-feedback">{!!$errors->first('iso')!!}</p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg-6 @if($errors->has('country_code'))has-danger @endif">
                            {!!Form::label('country_code','Country Code')!!}
                            {!!Form::text('country_code', old('country_code'), ['class'=>'form-control','placeholder'=>'Country Code'])!!}
                            @if($errors->has('country_code'))
                                <p class="help-block">{!!$errors->first('country_code')!!}</p>
                            @endif
                        </div>
                        <div class="col-lg-6">
                            {!!Form::label('suite_number','Suite Number')!!}
                            {!!Form::text('suite_number', old('suite_number'), ['class'=>'form-control','placeholder'=>'Suite Number'])!!}
                            @if($errors->has('suite_number'))
                                <p class="help-block">{!!$errors->first('suite_number')!!}</p>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid">
                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-secondary">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            {!!Form::close()!!}
            <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
@stop

@section('contentFooter')

@stop

resources/views/admin/pages/countries/index.blade.php
@extends('admin.layouts.master')

@section('contentHeader')

@stop

@section('page_title')
    Countries
@stop

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__body">
            <!--begin: Search Form -->
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">
                        <div class="form-group m-form__group row align-items-center">
                            <div class="col-md-4">
                                <div class="m-input-icon m-input-icon--left">
                                    <input type="text" class="form-control m-input m-input--solid"
                                           placeholder="Search..." id="generalSearch">
                                    <span class="m-input-icon__icon m-input-icon__icon--left">
                                        <span>
                                            <i class="la la-search"></i>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        <a href="{!! url()->route('admin.countries.create') !!}"
                           class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                                <span>
                                    <i class="m-nav__link-icon flaticon-add"></i>
                                    <span>
                                        New Country
                                    </span>
                                </span>
                        </a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            <!--end: Search Form -->
            <!--begin: Datatable -->
            <table class="table m-table m-table--head-bg-metal  table-striped" id="dataTable">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>ISO</th>
                    <th>Country Code</th>
                    <th>Suite Number</th>
                    <th>Actions</th>
                </tr>
                </thead>
            </table>
            <!--end: Datatable -->
        </div>
    </div>
@stop

@section('contentFooter')
    <script>
        $('#users_roles').selectpicker();

        var dTable = $('#dataTable').DataTable({
            ajax: {
                url: adminAjaxURL + 'datatable-countries',
                data: function (d) {
                    d.search['value'] = $('#generalSearch').val();
                }
            },
            columns: [
                {data: 'id', name: 'id', className: 'dt-center', searchable: false},
                {data: 'name', name: 'name', className: 'dt-center'},
                {data: 'iso', name: 'iso', className: 'dt-center'},
                {data: 'country_code', name: 'country_code', className: 'dt-center'},
                {data: 'suite_number', name: 'suite_number', className: 'dt-center'},
                {data: 'action', searchable: false, orderable: false, className: 'dt-center'},
            ],
            order: [[0, 'desc']]
        });

        $('#generalSearch').on('keydown keyup blur change', $.debounce(500, function () {
            dTable.draw();
        }));

        $('#users_roles').change($.debounce(500, function () {
            dTable.draw();
        }));


        $(document).on('click', '.deleteCountry', function (e) {
            e.preventDefault();
            if (confirm('Are you sure you want to delete this country?')) {
                $.ajax({
                    dataType: 'json',
                    method: 'delete',
                    url: adminURL + "countries/" + $(this).data('id'),
                    success: function (data) {
                        dTable.draw(false);
                    }
                });
            }
        });
    </script>
@stop